---
# tasks file for vpn
- name: insure open vpn is present on server
  package: name=openvpn state=latest

- name: generate open vpn config
  template: src=client.j2 dest={{ dest_file }} mode=0555

- name: start open vpn service on boot
  service: name=openvpn state=started enabled=yes

  
